---
title: "Untitled"
author: "Leah Jackson"
date: "11/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(tidyr)
aggregate_edited <- readRDS("individual_offense.RDS")
```


```{r}
count_df1 <- aggregate_edited %>% 
    group_by(sex, race, state_name) %>%
    count(offense_type) %>%
  filter(offense_type %in% "Aggravated Assault") #input$OffenseType
View(count_df1)
```

```{r}
aggregate_edited$age <- as.numeric(aggregate_edited$age)
count_df9 <- aggregate_edited %>% 
    group_by(age) %>%
    count(offense_type) %>%
  filter(offense_type %in% "Shoplifting") #input$OffenseType
View(count_df9)
```

```{r}
ggplot(    data= count_df9, 
             aes(   x= age, 
                    y= n)) +
        geom_density(stat="identity")+
      labs(y= "Number of Arrests", x= "Age", title= NULL) +
geom_vline(aes(xintercept=median(n)),color="red", linetype="dashed", size=1) +
  theme_minimal()
```

```{r}
ggplot(    data= aggregate_edited, 
             aes(age) 
                    y= n)) +
        geom_density(stat="identity")+
      labs(y= "Number of Arrests", x= "Age", title= NULL) +
  theme_minimal()
```

```{r}
ggplot(    data= count_df1, 
             aes(   x= reorder(sex, -n), 
                    y= n)) +
        geom_bar(stat="identity")

ggplot(    data= count_df1, 
             aes(   x= race, 
                    y= n)) +
        geom_bar(stat="identity")

ggplot(    data= count_df1, 
             aes(   x= reorder(state_name, -n), 
                    y= n)) +
        geom_bar(stat="identity") +theme_minimal()
```

```{r}
 count_df2 <- aggregate_edited %>% 
    filter (aggregate_edited$offense_type %in% "Aggravated Assault") %>% 
    count(offense_type, sex)
```

```{r}
View(count_df2)
```

```{r}
ggplot(    data= count_df2, 
             aes(   x= sex, 
                    y= n)) +
        geom_bar(stat="identity")
```

```{r}
 count_df3 <- aggregate_edited %>% 
    filter (aggregate_edited$offense_type %in% "Aggrevated Assault") %>% 
    count(offense_type, state_name)
```

```{r}
View(count_df3)
```

```{r}
ggplot(    data= count_df3, 
             aes(   x= state_name, 
                    y= n)) +
        geom_bar(stat="identity")
```

```{r}
 count_df4 <- aggregate_edited %>% 
    filter (aggregate_edited$offense_type %in% "Shoplifting") %>% 
    count(offense_type, race)
```

```{r}
View(count_df4)
```

```{r}
ggplot(    data= count_df4, 
             aes(   x= race, 
                    y= n)) +
        geom_bar(stat="identity")
```