---
title: "toto_LJ"
author: "Leah Jackson"
date: "10/20/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import library}
library(ggplot2)
library(dplyr)
```

```{r}
state_and_offense <- aggregate_edited %>%
  group_by(state_name, offense_type) %>%
  summarise(crimes = n())
View (table)
```

```{r}
count(sex, sta)
```

```{r}

off_shop <- filter(aggregate_edited, offense_type == "Shoplifting")
off_drug <- filter(aggregate_edited, offense_type == "Drug/Narcotic Violations")
off_assault <- filter(aggregate_edited, offense_type == "Simple Assault")

state_and_offense <- aggregate_edited %>%
  group_by(state_name, off_shop) %>%
  summarise(crimes = n())
View (state_and_offense)


```

# Bar: Offense Type by Sex, State, and Race

## Bar: Offense Type and Sex
```{r}
ggplot(data=aggregate_edited, aes(x=offense_type, fill=sex)) +
  geom_bar() +
  theme(legend.position = "right")
```
```{r}
ggplot(data=aggregate_edited, aes(x=sex, fill=offense_type)) +
  geom_bar() +
  theme(legend.position = "right")
```

## Bar: Offense Type and State
```{r}
ggplot(data=aggregate_edited, aes(x=state_name, fill=offense_type)) +
  geom_bar() +
  theme(legend.position = "right")
```

## Bar: Offense Type and Race
```{r}
ggplot(data=aggregate_edited, aes(x=race, fill=offense_type)) +
  geom_bar() +
  theme(legend.position = "right")
```


## Offense Type by Age

```{r}
ggplot(aggregate_edited, aes(x= age)) + 
geom_histogram(color = "darkblue", 
               fill= "lightblue") + 
geom_vline(xintercept = mean(aggregate_edited$age), 
           linetype = "dashed", 
           size = 2, 
           color = "black")
```


## Time & Crime: Choose An Offense type and See Its prevelence by time

